/**
 * Print CAF react-builder command cheat sheet.
 *
 * Usage: npm run help
 */

const lines = [
  '',
  'CAF React Builder — all commands',
  '================================',
  '',
  'Run every command from:',
  '  category-ajax-filter-pro/react-builder/',
  '',
  '  cd C:\\xampp\\htdocs\\new-test\\wp-content\\plugins\\category-ajax-filter-pro\\react-builder',
  '',
  'Sites',
  '-----',
  '  Pro dev:   http://localhost/new-test/wp-admin/edit.php?post_type=caf_posts',
  '  Free test: http://localhost/test-caf-old/wp-admin/edit.php?post_type=caf_posts',
  '',
  'Commands',
  '--------',
  '',
  '  npm run help',
  '    Show this cheat sheet.',
  '',
  '  npm start',
  '    Daily Pro development — webpack watch mode.',
  '    Rebuilds on save → react-builder/build/ (~12 MB Pro bundle).',
  '    Does NOT touch the free plugin.',
  '    When: editing React UI every day.',
  '',
  '  npm run build',
  '    One-off full Pro production build → react-builder/build/.',
  '    Does NOT touch the free plugin.',
  '    When: you need a fresh Pro bundle without watch mode, or Pro admin',
  '          looks wrong after running build:free / release:free.',
  '',
  '  npm run build:free',
  '    Build free-tier JS + sync to free plugin for local testing.',
  '    Steps: build build-free/ → copy to free plugin → strip Pro CSS.',
  '    When: test free limits on test-caf-old after React changes.',
  '    Does NOT create a release folder or zip.',
  '',
  '  npm run smoke:free',
  '    Scan Free react-builder/build for Guideline 5 regressions',
  '    (banned Pro markers absent; lock-chrome stubs present).',
  '    When: after build:free, or before release:free.',
  '',
  '  Free Woo runtime',
  '  ------------------',
  '  build:free syncs only the curated files under scripts/free-plugin/.',
  '  Pro includes/woocommerce/ is never copied wholesale into free.',
  '  Woo is included by default; override with $env:CAF_BUILD_WOO=\"0\".',
  '',
  '  npm run release:free',
  '    Prepare FREE plugin for WordPress upload (folder only, no zip).',
  '    Steps: free build → release sync → stage clean folder → smoke:free.',
  '    Output: test-caf-old/.../category-ajax-filter/dist/category-ajax-filter/',
  '    When: publishing a new free version (WP.org or customers).',
  '',
  '  npm run release:pro',
  '    Prepare PRO plugin for WordPress upload (folder only, no zip).',
  '    Steps: Pro build → strip source maps → stage clean folder.',
  '    Output: category-ajax-filter-pro/dist/category-ajax-filter-pro/',
  '    When: publishing a new Pro version.',
  '',
  '  npm run release:free:debug',
  '    FREE support/debug package — unminified JS + .map + react-builder/src.',
  '    Output: .../category-ajax-filter/dist-debug/category-ajax-filter/',
  '    When: diagnosing CAF Support Report stack traces on a test site.',
  '    Do NOT ship to WP.org or customers.',
  '',
  '  npm run release:pro:debug',
  '    PRO support/debug package — unminified JS + .map + react-builder/src.',
  '    Output: .../category-ajax-filter-pro/dist-debug/category-ajax-filter-pro/',
  '    When: diagnosing builder crashes with readable stack maps.',
  '    Do NOT ship to customers.',
  '',
  'Manual zip for WordPress upload',
  '-------------------------------',
  '  Scripts do NOT create zip files. After release:free or release:pro:',
  '',
  '    1. Open the dist/ folder listed above',
  '    2. Right-click the PLUGIN FOLDER (not files inside it)',
  '       → Compress to ZIP',
  '    3. Plugins → Add New → Upload Plugin',
  '',
  '  Correct zip structure:',
  '    category-ajax-filter-pro.zip',
  '      └── category-ajax-filter-pro/',
  '            ├── caf-pro.php',
  '            └── ...',
  '',
  'Quick decision guide',
  '--------------------',
  '  Editing UI daily           → npm start',
  '  Test Pro after changes     → refresh new-test admin',
  '  Test free limits locally   → npm run build:free',
  '  Publish FREE               → npm run release:free → zip folder manually',
  '  Publish PRO                → npm run release:pro → zip folder manually',
  '  Debug CAF Support Report   → npm run release:free:debug (or :pro:debug)',
  '  Pro admin shows wrong UI   → npm run build',
  '',
  'Output folders',
  '--------------',
  '  react-builder/build/       Full Pro bundle (Pro site loads this)',
  '  react-builder/build-free/  Free-tier intermediate build',
  '  free react-builder/build/  What free WordPress loads after sync',
  '  pro  dist/category-ajax-filter-pro/   Upload-ready Pro folder',
  '  free dist/category-ajax-filter/       Upload-ready free folder',
  '  free dist-debug/...                   Debug free (maps + src)',
  '  pro  dist-debug/...                   Debug Pro (maps + src)',
  '',
  'Optional env',
  '------------',
  '  $env:CAF_FREE_PLUGIN_PATH = "C:\\path\\to\\category-ajax-filter"',
  '  Use if your free plugin is not at test-caf-old.',
  '',
  'More detail: react-builder/BUILD.md',
  '',
];

console.log(lines.join('\n'));
