import { fModuleStyle } from "../../../FilterComponents/styleData";

export const getWooAttributeSwatchModuleTemplate = () => (
    {
      type: "module",
      title: "Attribute Swatch",
      style: {
        ...fModuleStyle,
        container: {
          ...fModuleStyle.container,
          desktop: {
            ...fModuleStyle.container.desktop,
            default: {
              ...fModuleStyle.container.desktop.default,
              width: "100%",
              height: "auto",
              position: "relative",
              paddingTop: "10px",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              marginTop: "0",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "rgb(255,255,255)",
              color: "#4c5866",
              fontFamily: "Open Sans",
              fontSize: "14px",
              display: "flex",
              flexFlow: "column",
              alignItems: "flex-start",
              justifyContent: "flex-start",
              gap: "0px",
              float: "none",
              boxShadow: "0px 0px 0px 0px  #333333",
              top: "auto",
              right: "auto",
              bottom: "auto",
              left: "auto",
            },
          },
        },
        header: {
          ...fModuleStyle.header,
          desktop: {
            ...fModuleStyle.header.desktop,
            default: {
              ...fModuleStyle.header.desktop.default,
              width: "100%",
              height: "auto",
              position: "relative",
              top: "0",
              bottom: "0",
              left: "0",
              right: "0",
              paddingTop: "0px",
              paddingRight: "0",
              paddingBottom: "10px",
              paddingLeft: "0",
              marginTop: "0",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "rgba(255,255,255,0)",
              color: "#000",
              fontFamily: "DM Sans",
              fontWeight: "400",
              fontSize: "20px",
              boxShadow: "0px 0px 0px 0px  #333333",
              display: "flex",
            },
          },
        },
        input: {
          ...fModuleStyle.input,
          desktop: {
            ...fModuleStyle.input.desktop,
            default: {
              ...fModuleStyle.input.desktop.default,
              width: "18px",
              height: "18px",
              position: "relative",
              paddingTop: "0px",
              paddingRight: "0",
              paddingBottom: "0px",
              paddingLeft: "0",
              marginTop: "0",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "#ffffff",
              color: "rgb(255,255,255)",
              fontFamily: "Montserrat",
              fontWeight: "700",
              fontSize: "22px",
              borderTopWidth: "2px",
              borderRightWidth: "2px",
              borderBottomWidth: "2px",
              borderLeftWidth: "2px",
              borderTopColor: "rgb(209,213,220)",
              borderRightColor: "rgb(209,213,220)",
              borderBottomColor: "rgb(209,213,220)",
              borderLeftColor: "rgb(209,213,220)",
              borderTopStyle: "solid",
              borderRightStyle: "solid",
              borderBottomStyle: "solid",
              borderLeftStyle: "solid",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              borderBottomLeftRadius: "4px",
              borderBottomRightRadius: "4px",
            },
            selected: {
              ...fModuleStyle.input.desktop.selected,
              backgroundColor: "rgb(0,0,0)",
              borderTopWidth: "2px",
              borderRightWidth: "2px",
              borderBottomWidth: "2px",
              borderLeftWidth: "2px",
              borderTopColor: "rgb(3,3,3)",
              borderRightColor: "rgb(3,3,3)",
              borderBottomColor: "rgb(3,3,3)",
              borderLeftColor: "rgb(3,3,3)",
              borderTopStyle: "solid",
              borderRightStyle: "solid",
              borderBottomStyle: "solid",
              borderLeftStyle: "solid"
            }
          },
        },
        meta: {
          ...fModuleStyle.meta,
          desktop: {
            ...fModuleStyle.meta.desktop,
            default: {
              ...fModuleStyle.meta.desktop.default,
              width: "100%",
              height: "auto",
              position: "relative",
              paddingTop: "0px",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              marginTop: "0",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "rgba(255,255,255,0)",
              fontFamily: "Open Sans",
              textTransform: "capitalize",
              fontSize: "16px",
              color: "#dd3333",
              display: "flex",
              flexFlow: "row",
              alignItems: "center",
              justifyContent: "flex-start",
              gap: "10px",
              float: "none",
              flexWrap: "wrap",
              boxShadow: "0px 0px 0px 0px  #333333"
            },
          },
        },
        mainmeta: {
          ...fModuleStyle.mainmeta,
          desktop: {
            ...fModuleStyle.mainmeta.desktop,
            default: {
              ...fModuleStyle.mainmeta.desktop.default,
              width: "100%",
              height: "auto",
              position: "relative",
              paddingTop: "10px",
              paddingRight: "0",
              paddingBottom: "0",
              paddingLeft: "0",
              marginTop: "0",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "#ffffff",
              fontFamily: "Open Sans",
              textTransform: "capitalize",
              fontSize: "16px",
              color: "#dd3333",
              display: "flex",
              flexFlow: "row",
              alignItems: "center",
              justifyContent: "flex-start",
              gap: "15px",
              float: "none",
              flexWrap: "wrap"
            },
          },
        },
        selectmeta: {
          ...fModuleStyle.selectmeta,
          desktop: {
            ...fModuleStyle.selectmeta.desktop,
            default: {
              ...fModuleStyle.selectmeta.desktop.default,
              width: "100%",
              height: "auto",
              position: "relative",
              paddingTop: "10px",
              paddingRight: "10px",
              paddingBottom: "10px",
              paddingLeft: "10px",
              marginTop: "0px",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "#ffffff",
              fontFamily: "Open Sans",
              textTransform: "capitalize",
              fontSize: "16px",
              color: "#dd3333",
              display: "flex",
              flexFlow: "row",
              alignItems: "center",
              justifyContent: "space-between",
              gap: "0px",
              float: "none",
              borderTopLeftRadius: "6px",
              borderTopRightRadius: "6px",
              borderBottomLeftRadius: "6px",
              borderBottomRightRadius: "6px",
              borderTopColor: "#c6bdbd",
              borderRightColor: "#c6bdbd",
              borderBottomColor: "#c6bdbd",
              borderLeftColor: "#c6bdbd",
              borderTopWidth: "1px",
              borderRightWidth: "1px",
              borderBottomWidth: "1px",
              borderLeftWidth: "1px",
              borderTopStyle: "solid",
              borderRightStyle: "solid",
              borderBottomStyle: "solid",
              borderLeftStyle: "solid"
            },
          },
        },
        meta1: {
          ...fModuleStyle.meta1,
          desktop: {
            ...fModuleStyle.meta1.desktop,
            default: {
              ...fModuleStyle.meta1.desktop.default,
              width: "auto",
              height: "auto",
              position: "relative",
              paddingTop: "5px",
              paddingRight: "5px",
              paddingBottom: "5px",
              paddingLeft: "5px",
              marginTop: "0px",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "#ffffff",
              fontFamily: "DM Sans",
              textTransform: "capitalize",
              fontSize: "16px",
              color: "rgb(3,3,3)",
              display: "flex",
              flexFlow: "row",
              alignItems: "center",
              justifyContent: "flex-start",
              gap: "5px",
              float: "none",
              borderTopLeftRadius: "0px",
              borderTopRightRadius: "0px",
              borderBottomLeftRadius: "0px",
              borderBottomRightRadius: "0px",
              borderTopColor: "rgb(235,230,231)",
              borderRightColor: "rgb(235,230,231)",
              borderBottomColor: "rgb(235,230,231)",
              borderLeftColor: "rgb(235,230,231)",
              borderTopWidth: "1px",
              borderRightWidth: "1px",
              borderBottomWidth: "1px",
              borderLeftWidth: "1px",
              borderTopStyle: "solid",
              borderRightStyle: "solid",
              borderBottomStyle: "solid",
              borderLeftStyle: "solid",
              fontStyle: "normal",
              textDecoration: "inherit",
              boxShadow: "0px 0px 0px 0px  #333333"
            },
            hover: {
              ...fModuleStyle.meta1.desktop.hover,
              backgroundColor : "rgb(246,247,251)"
            },
            selected: {
              ...fModuleStyle.meta1.desktop.selected,
              backgroundColor : "rgb(246,247,251)"
            },
          },
        },
        meta2: {
          ...fModuleStyle.meta2,
          desktop: {
            ...fModuleStyle.meta2.desktop,
            default: {
              ...fModuleStyle.meta2.desktop.default,
              display: "flex",
              flexFlow: "row",
              alignItems: "center",
              justifyContent: "center",
              gap: "0px",
              float: "none"
            },
          },
        },
        meta3: {
          ...fModuleStyle.meta3,
          desktop: {
            ...fModuleStyle.meta3.desktop,
            default: {
              ...fModuleStyle.meta3.desktop.default,
              display: "flex",
              flexFlow: "row",
              alignItems: "center",
              justifyContent: "flex-start",
              gap: "5px",
              float: "none"
            },
          },
        },
        meta4: {
          ...fModuleStyle.meta4,
          desktop: {
            ...fModuleStyle.meta4.desktop,
            default: {
              ...fModuleStyle.meta4.desktop.default,
              display: "flex",
              flexFlow: "row",
              alignItems: "flex-start",
              justifyContent: "flex-start",
              gap: "3px",
              float: "none"
            },
          },
        },
        icon: {
          ...fModuleStyle.icon,
          desktop: {
            ...fModuleStyle.icon.desktop,
            default: {
              ...fModuleStyle.icon.desktop.default,
              fontSize: "18px",
              color: "rgb(0,0,0)"
            },
          },
        },
        icon2: {
          ...fModuleStyle.icon2,
          desktop: {
            ...fModuleStyle.icon2.desktop,
            default: {
              ...fModuleStyle.icon2.desktop.default,
              fontSize: "16px",
              color: "#dd3333"
            },
          },
        },
        icon3: {
          ...fModuleStyle.icon3,
          desktop: {
            ...fModuleStyle.icon3.desktop,
            default: {
              ...fModuleStyle.icon3.desktop.default,
              fontSize: "16px",
              color: "#dd3333"
            },
          },
        },
        selecticon: {
          ...fModuleStyle.selecticon,
          desktop: {
            ...fModuleStyle.selecticon.desktop,
            default: {
              ...fModuleStyle.selecticon.desktop.default,
              fontSize: "16px",
              color: "#dd3333"
            },
          },
        },
        count: {
          ...fModuleStyle.count,
          desktop: {
            ...fModuleStyle.count.desktop,
            default: {
              ...fModuleStyle.count.desktop.default,
              width: "auto",
              height: "auto",
              paddingTop: "0px",
              paddingRight: "0px",
              paddingBottom: "0px",
              paddingLeft: "0px",
              marginTop: "0px",
              marginRight: "0",
              marginBottom: "0",
              marginLeft: "0",
              backgroundColor: "#ffffff00",
              fontFamily: "Open Sans",
              textTransform: "capitalize",
              fontSize: "16px",
              color: "rgb(96,96,96)",
              fontWeight: "300"
            },
          },
        },
      },
      key: "woo_attribute_swatch",
      settings: {
        taxonomy_data: [],
        taxonomy_relation: "OR",
        category_relation: "OR",
        meta_relation: "IN",
        custom_class: "",
        admin_label: "",
        predefined_terms: [],
        cf_predefined_terms: [],
        label: {
          is_label: "false",
          value: "Label",
          icons: {
            visibility: false,
            icon: "",
            position: "before-label",
            type: "icon"
          }
        },
        multiple_term: "false",
        show_checkbox: "false",
        show_icon: "true",
        term_visual: "icon",
        hide_term_label: "true",
        show_count: "false",
        count_separator: "brackets",
        enable_toggle: "false",
        toggle_position: "right",
        close_toggle: "false",
        data_source: "taxonomy",
        custom_field_data: [],
        visibility: {
          mobile: "false",
          tablet: "false",
          desktop: "false"
        }
      }
    }
);
